### ISSUE TITLE
Скрывать форму комментария на Хабре

### ISSUE THREAD

**Issue by yarkovaleksei** [MarisKori/Toster-Comfort#10]
Наткнулся на такую статью: [Ответ на последний комментарий](https://habr.com/ru/post/445990/). Предлагаю сделать такую опцию.

**Comment by MarisKori** [comment]
Ещё одну кнопку? Сомнительно. Тогда проще заменить текст "Написать комментарий" на "Написать корневой комментарий".

**Comment by yarkovaleksei** [comment]
Ну можно обернуть форму в спойлер, чтобы по клику разворачивать

**Comment by MarisKori** [comment]
Спойлер там уже есть. Форма сворачивает при нажатии "ответить" под любым комментарием. Только где найти код, который отвечает за спойлер?

**Comment by MarisKori** [comment]
Там еще проблема, что контент скрипт в своей песочнице варится, хоть и может влиять на DOM.

**Comment by MarisKori** [comment]
Вроде сделал.
