### ISSUE TITLE
Привести код к единому стилю

### ISSUE THREAD

**Issue by yarkovaleksei** [MarisKori/Toster-Comfort#4]
Неплохо было бы привести код к единому стилю. Внедрить **eslint** и т. п. Если автор не против, то я мог бы заняться на досуге.

**Comment by MarisKori** [comment]
Не вижу особой пользы в едином стиле.
MyFunc или myFunc или my_func, let или const - лишь бы не было ляпов, когда сложность вычислений внезапно становится O(N*N), например. Я за человеческие названия и минимализм (или модульность) - имхо, это основа читабельности. Остальное не так важно.
