### ISSUE TITLE
Добавить отображение тегов в блоке "САМОЕ ИНТЕРЕСНОЕ ЗА 24 ЧАСА"

### ISSUE THREAD

**Issue by yarkovaleksei** [MarisKori/Toster-Comfort#5]
Я бы добавил отображение тегов в блоке "САМОЕ ИНТЕРЕСНОЕ ЗА 24 ЧАСА". При наведении на заголовок вопроса делать запрос и выводить список тегов.
![untitled](https://user-images.githubusercontent.com/6022892/47912028-3e8b7900-dea8-11e8-95a2-5ce09bd91328.png)
Например на скрине интригующий заголовок "Почему этот код выполняется только один раз?".
Переходим, а там C#, Unity и прочие не интересующие теги.
Было бы круто.

**Comment by MarisKori** [comment]
Теоретически можно. Но цена за это - хранение тегов в кэше. Сейчас теги не сохраняются в кэш вопросов. А когда они будут сохраняться, база будет распухать быстрее.

С другой стороны, если расширение будет знать про теги, то можно подключить ещё много функционала (показ всех тегов в списке вопросов, чёрный список тегов). Так что да, придётся сделать.

**Comment by yarkovaleksei** [comment]
Можно еще вместо LocalStorage использовать IndexedDB, чтобы в ограничение размера базы не упереться.

**Comment by MarisKori** [comment]
Готово.
