### ISSUE TITLE
Перестал показывать процент закрытых вопросов

### ISSUE THREAD

**Issue by NikolayPetyukh** [MarisKori/Toster-Comfort#6]
У всех пользователей процент в вопросов с выбранным решение 0
![f96419db-977a-4c9b-a1ae-38f630827960](https://user-images.githubusercontent.com/8134986/51309754-c6b40000-1a4d-11e9-9858-7bcc68f43b3d.png)

**Comment by MarisKori** [comment]
Да, вижу. Видимо, обновили что-то на сайте. Исправлю.

**Comment by yarkovaleksei** [comment]
Ну не у всех же, смотрите внимательно.

**Comment by NikolayPetyukh** [comment]
@yarkovaleksei я про черные проценты

**Comment by yarkovaleksei** [comment]
@NikolayPetyukh вот это я сумничал )) Я думал про зеленые же.

**Comment by MarisKori** [comment]
Опубликовал исправление.
В браузерах расширение обновиться через несколько часов.
